-- require("auto-reload")
hs.loadSpoon("EmmyLua")
-- require("vim-mode")
-- require("only-show-alacritty")
-- require("keyboard.yabai")
-- require("keyboard.hyper")
require("keyboard.arrows")
-- require("keyboard.apps")
-- require("keyboard.tmux")
hs.notify.new({ title = "Hammerspoon", informativeText = "Ready to rock!! 🤘" }):send()
