hs.loadSpoon("EmmyLua")
require("auto-reload")
require("vim-mode")
require("only-show-alacritty")
require("keyboard.yabai")
require("keyboard.hyper")
-- require("keyboard.tmux")
hs.notify.new({ title = "Hammerspoon", informativeText = "Ready to rock!! 🤘" }):send()
