return {
  "WhoIsSethDaniel/mason-tool-installer.nvim",
  cmd = { "MasonToolsInstall", "MasonToolsUpdate", "MasonToolsClean" },
  opts = {
    ensure_installed = {
      "astro-language-server",
      "bash-debug-adapter",
      "bash-language-server",
      "cspell",
      "debugpy",
      "delve",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "emmet-language-server",
      "eslint-lsp",
      "gofumpt",
      "goimports",
      "goimports-reviser",
      "gomodifytags",
      "gopls",
      "graphql-language-service-cli",
      "hadolint",
      "impl",
      "js-debug-adapter",
      "json-lsp",
      "lua-language-server",
      "markdownlint",
      "marksman",
      "prettier",
      "prettierd",
      "prisma-language-server",
      "pyright",
      "ruff-lsp",
      "shfmt",
      "stylua",
      "tailwindcss-language-server",
      "typescript-language-server",
      "yaml-language-server",
    },
  },
}
